#!/bin/sh

# Arguments
INPUT_DIR=`pwd`
echo "Instalation directory is: $INPUT_DIR"
FILE="{$INPUT_DIR}/tmp.txt"
# Save the Instalation path
echo $FILE
echo $INPUT_DIR > $FILE

# Package
PACKAGE="debian-chroot"
DNAME="Debian Chroot"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:${PATH}"
CHROOTTARGET=`realpath ${INSTALL_DIR}/var/chroottarget`


start_daemon ()
{
    # Mount if install is finished
    if [ -f ${INSTALL_DIR}/var/installed ]; then
        # Make sure we don't mount twice
        grep -q "${CHROOTTARGET}/proc " /proc/mounts || mount -t proc proc ${CHROOTTARGET}/proc
        grep -q "${CHROOTTARGET}/sys " /proc/mounts || mount -t sysfs sys ${CHROOTTARGET}/sys
        grep -q "${CHROOTTARGET}/dev " /proc/mounts || mount -o bind /dev ${CHROOTTARGET}/dev
        grep -q "${CHROOTTARGET}/dev/pts " /proc/mounts || mount -o bind /dev/pts ${CHROOTTARGET}/dev/pts
        [ ! -d ${CHROOTTARGET}${INPUT_DIR} ] && mkdir -p ${CHROOTTARGET}${INPUT_DIR}
        grep -q "${CHROOTTARGET}${INPUT_DIR} " ${INPUT_DIR} || mount -o bind ${INPUT_DIR} ${CHROOTTARGET}${INPUT_DIR}

        # Start all services                                                            
        ${INSTALL_DIR}/app/start.py                                                     
    fi                                                                                  
}                                                                                       
                                                                                        
stop_daemon ()                                                                          
{                                                                                       
    # Stop running services                                                             
    ${INSTALL_DIR}/app/stop.py                                                          
                                                                                        
    # Unmount                                                                           
    umount ${CHROOTTARGET}/dev/pts                                                      
    umount ${CHROOTTARGET}/dev                                                          
    umount ${CHROOTTARGET}/sys                                                          
    umount ${CHROOTTARGET}/proc                                                         
    umount ${CHROOTTARGET}${INPUT_DIR}                                                 
}                                                                                       
                                                                                        
daemon_status ()                                                                        
{                                                                                       
    `grep -q "${CHROOTTARGET}/proc " /proc/mounts` && `grep -q "${CHROOTTARGET}/sys " /proc/mounts` && `grep -q "${CHROOTTARGET}dev " /proc/mounts` && `grep -p "${CHROOTTARGET}/dev/pts " /proc/mounts`
}                                                                                       
                                                                                        
                                                                                        
case $1 in                                                                              
    start)                                                                              
        if daemon_status; then                                                          
            echo ${DNAME} is already running                                            
            exit 0                                                                      
        else                                                                            
            echo Starting ${DNAME} ...                                                  
            start_daemon                                                                
            exit $?                                                                     
        fi                                                                              
        ;;                                                                              
    stop)                                                                               
        if daemon_status; then                                                          
            echo Stopping ${DNAME} ...                                                  
            stop_daemon                                                                 
            exit 0                                                                      
        else                                                                            
            echo ${DNAME} is not running                                                
            exit 0                                                                      
        fi                                                                              
        ;;                                                                              
    status)                                                                             
        if daemon_status; then                                                          
            echo ${DNAME} is running                                                    
            exit 0                                                                      
        else                                                                            
            echo ${DNAME} is not running                                                
            exit 1                                                                      
        fi                                                                              
        ;;                                                                              
    chroot)                                                                             
        # start interactive shell to source /etc/profile                                
        chroot ${CHROOTTARGET}/ /bin/bash -l                                            
        ;;                                                                              
    *)                                                                                  
        exit 1                                                                          
        ;;                                                                              
esac                                                                                    